
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://shsfzddxzauwkgctnbxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoc2Z6ZGR4emF1d2tnY3RuYnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODE5NjksImV4cCI6MjA1NzQ1Nzk2OX0.YRUErDD6k8R4SJSdGx6-Ak-P9LXSiAOUhhNTQ5Gr5QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
